### ISSUE TITLE
Explodeitmite crash

### ISSUE THREAD

**Issue by FunshineX** [diesieben07/Modjam-4#1]
Explodeitmite sometimes crashes our server on tick:

Description: Ticking block entity

java.lang.OutOfMemoryError: Java heap space
	at java.util.HashMap.resize(HashMap.java:584)
	at java.util.HashMap.addEntry(HashMap.java:883)
	at java.util.HashMap.put(HashMap.java:509)
	at java.util.HashSet.add(HashSet.java:217)
	at net.minecraft.world.Explosion.func_77278_a(Explosion.java:95)
	at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:898)
	at net.minecraft.world.World.func_72876_a(World.java:2352)
	at mod.badores.ore.Explodeitmite.tick(Explodeitmite.java:36)
	at mod.badores.blocks.TileEntityBadOre.fireTick(TileEntityBadOre.java:35)
	at mod.badores.blocks.TileEntityBadOre.func_145845_h(TileEntityBadOre.java:21)
	at net.minecraft.world.World.func_72939_s(World.java:1888)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:500)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:620)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:326)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:531)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:414)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:669)

**Comment by Claycorp** [comment]
This issue still exists or is the mod dead as this is almost a year old issue?
http://pastebin.com/pVbbU1dX

**Comment by Ivorforce** [comment]
Well, part of both. We did want to release a bugfix update, but kind of forgot about it. Might get it done the following week or so :)

**Comment by Claycorp** [comment]
Still hope that this gets fixed! Looking forward to using the mod.

**Comment by diesieben07** [comment]
The problem is that neither of us can reproduce the bug. But I'll try something later that might fix it.

**Comment by Claycorp** [comment]
Well if you can't pinpoint it can you add the ability to disable ores? I don't know how it happens as minecraft just locks up and then eventually the JVM crashes. I can do some testing to see if i can find it myself.

**Comment by Ivorforce** [comment]
I already added *that* functionality - just not released yet.

**Comment by Claycorp** [comment]
:O Why not!
Don't hide those handy features!

**Comment by Claycorp** [comment]
Well im going to assume this isn't getting fixed.
Can you push whatever you have/any "dev" builds to curseforge? As it can't be any worse that what's there already.
